# permissions for end users to view groupmappings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: groupmapping-viewer-role
rules:
- apiGroups:
  - argocd.codemug.io
  resources:
  - groupmappings
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - argocd.codemug.io
  resources:
  - groupmappings/status
  verbs:
  - get
