# permissions for end users to edit groupmappings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: groupmapping-editor-role
rules:
- apiGroups:
  - argocd.codemug.io
  resources:
  - groupmappings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - argocd.codemug.io
  resources:
  - groupmappings/status
  verbs:
  - get
