
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - argocd.codemug.io
  resources:
  - groupmappings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - argocd.codemug.io
  resources:
  - groupmappings/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - argocd.codemug.io
  resources:
  - rolemappings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - argocd.codemug.io
  resources:
  - rolemappings/status
  verbs:
  - get
  - patch
  - update
