# permissions for end users to edit rolemappings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rolemapping-editor-role
rules:
- apiGroups:
  - argocd.codemug.io
  resources:
  - rolemappings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - argocd.codemug.io
  resources:
  - rolemappings/status
  verbs:
  - get
