## Append samples you want in your CSV to this file as resources ##
resources:
- codemug.io_v1beta1_argocdgroupmapping.yaml
- codemug.io_v1beta1_argocdrolemapping.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
