---
# permissions for end users to view groupmappings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "argocd-rbac-controller.fullname" . }}
rules:
  - apiGroups:
      - argocd.codemug.io
    resources:
      - groupmappings
      - rolemappings
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - argocd.codemug.io
    resources:
      - groupmappings/status
      - rolemappings/status
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
