---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "argocd-rbac-controller.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "argocd-rbac-controller.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "argocd-rbac-controller.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
